CREATE TABLE app_users (
  user_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email              VARCHAR2(255) NOT NULL UNIQUE,
  password_hash      VARCHAR2(255) NOT NULL,
  full_name          VARCHAR2(255) NOT NULL,
  role_code          VARCHAR2(30) NOT NULL,
  company_name       VARCHAR2(255),
  is_active          NUMBER(1) DEFAULT 1 NOT NULL,
  created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_role_code CHECK (role_code IN ('ADMIN', 'CLIENT_STANDARD', 'CLIENT_PREMIUM')),
  CONSTRAINT chk_user_active CHECK (is_active IN (0, 1))
);

CREATE TABLE documents (
  document_id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_type                   VARCHAR2(40) NOT NULL,
  title                      VARCHAR2(255) NOT NULL,
  description                VARCHAR2(1000),
  visibility_tier            VARCHAR2(30) NOT NULL,
  current_version_id         NUMBER,
  is_active                  NUMBER(1) DEFAULT 1 NOT NULL,
  created_by_user_id         NUMBER NOT NULL,
  created_at                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_doc_type CHECK (doc_type IN ('REFERENCE', 'CERTIFICATE', 'TRAINER_PROFILE', 'BIO', 'CV', 'OFFERING')),
  CONSTRAINT chk_visibility_tier CHECK (visibility_tier IN ('PUBLIC_CLIENTS', 'STANDARD_AND_PREMIUM', 'PREMIUM_ONLY')),
  CONSTRAINT chk_doc_active CHECK (is_active IN (0, 1)),
  CONSTRAINT fk_documents_created_by FOREIGN KEY (created_by_user_id) REFERENCES app_users(user_id)
);

CREATE TABLE document_versions (
  version_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id                 NUMBER NOT NULL,
  version_no                  NUMBER NOT NULL,
  storage_bucket              VARCHAR2(255) NOT NULL,
  storage_namespace           VARCHAR2(255) NOT NULL,
  storage_object_name         VARCHAR2(1024) NOT NULL,
  original_filename           VARCHAR2(255) NOT NULL,
  content_type                VARCHAR2(120) NOT NULL,
  file_size_bytes             NUMBER NOT NULL,
  sha256_checksum             VARCHAR2(64) NOT NULL,
  uploaded_by_user_id         NUMBER,
  upload_source               VARCHAR2(30) NOT NULL,
  webhook_event_id            VARCHAR2(120),
  is_current                  NUMBER(1) DEFAULT 0 NOT NULL,
  created_at                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_doc_version UNIQUE (document_id, version_no),
  CONSTRAINT chk_upload_source CHECK (upload_source IN ('ADMIN_PANEL', 'WEBHOOK')),
  CONSTRAINT chk_is_current CHECK (is_current IN (0, 1)),
  CONSTRAINT fk_versions_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_versions_uploaded_by FOREIGN KEY (uploaded_by_user_id) REFERENCES app_users(user_id)
);

ALTER TABLE documents
  ADD CONSTRAINT fk_documents_current_version FOREIGN KEY (current_version_id)
  REFERENCES document_versions(version_id);

CREATE UNIQUE INDEX uq_doc_current_active_only
  ON document_versions (CASE WHEN is_current = 1 THEN document_id END);

CREATE INDEX idx_doc_versions_doc_current ON document_versions(document_id, is_current);
CREATE INDEX idx_doc_versions_created_at ON document_versions(created_at);

CREATE TABLE document_acl (
  acl_id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id                 NUMBER NOT NULL,
  user_id                     NUMBER NOT NULL,
  can_view                    NUMBER(1) DEFAULT 1 NOT NULL,
  can_download                NUMBER(1) DEFAULT 1 NOT NULL,
  created_at                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_document_acl UNIQUE (document_id, user_id),
  CONSTRAINT chk_acl_view CHECK (can_view IN (0, 1)),
  CONSTRAINT chk_acl_download CHECK (can_download IN (0, 1)),
  CONSTRAINT fk_acl_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_acl_user FOREIGN KEY (user_id) REFERENCES app_users(user_id)
);

CREATE TABLE access_logs (
  access_log_id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                     NUMBER NOT NULL,
  document_id                 NUMBER NOT NULL,
  version_id                  NUMBER NOT NULL,
  action_type                 VARCHAR2(30) NOT NULL,
  ip_address                  VARCHAR2(64),
  user_agent                  VARCHAR2(1000),
  request_id                  VARCHAR2(80),
  created_at                  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_action_type CHECK (action_type IN ('VIEW', 'DOWNLOAD', 'ADMIN_UPDATE', 'WEBHOOK_UPLOAD')),
  CONSTRAINT fk_access_user FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT fk_access_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_access_version FOREIGN KEY (version_id) REFERENCES document_versions(version_id)
);

CREATE INDEX idx_access_logs_user_created ON access_logs(user_id, created_at);
CREATE INDEX idx_access_logs_document_created ON access_logs(document_id, created_at);

CREATE TABLE webhook_events (
  webhook_event_id            VARCHAR2(120) PRIMARY KEY,
  source_system               VARCHAR2(80) NOT NULL,
  received_at                 TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  status                      VARCHAR2(20) NOT NULL,
  error_message               VARCHAR2(2000),
  processed_at                TIMESTAMP,
  CONSTRAINT chk_webhook_status CHECK (status IN ('RECEIVED', 'PROCESSED', 'FAILED'))
);
